Build Latest:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/morgul/pogo-pc:latest -t registry.gitlab.com/morgul/pogo-pc:$CI_BUILD_REF_NAME .
     - docker push registry.gitlab.com/morgul/pogo-pc:latest
     - docker push registry.gitlab.com/morgul/pogo-pc:$CI_BUILD_REF_NAME
